apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  voulmeName: "efs-static"
  resources:
    requests:
      storage: 5Gi