kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx
  # these labels are replica set labels
  labels:
    app:frontend
    tier:web
spec:
  replicas: 3
  selector:
  #replicaset use these labels to find the pods for creating desired number of replicas
  matchLabels:
    app: frontend
    tier: web
    # pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
      spec:
        conatiners:
        - name: nginx
          image: nginx



